#!/usr/bin/env python3

import re
from gradelib import *

r = Runner(save("xv6.out"))

@test(5, "answers-boot.txt")
def test_answers():
    # just a simple sanity check, will be graded manually
    check_answers("answers-boot.txt")

@test(5, "xv6 boots")
def test_usertests():
    r.run_qemu(shell_script([
        'ls'
    ]), timeout=1000)
    r.match('README')

run_tests()
