#!/usr/bin/env python3

import re
from gradelib import *

r = Runner(save("xv6.out"))

@test(10, "answers-boot.txt")
def test_answers():
    # just a simple sanity check, will be graded manually
    check_answers("answers-boot.txt")

@test(0, "usertests")
def test_usertests():
    r.run_qemu(shell_script([
        'usertests -q'
    ]), timeout=1000)
    r.match('^ALL TESTS PASSED$')

run_tests()
